// 默认字段列表数据
export const FIELD_TABLE_DATA = [
  {
    fieldName: 'id',
    fieldComment: '主键',
    fieldType: ['bigint'],
    columnSize: 19,
    scale: 0,
    fieldDefault: '',
    primaryKey: true,
    nullable: false,
  },
  {
    fieldName: 'sort',
    fieldComment: '排序',
    fieldType: ['int'],
    columnSize: 19,
    scale: 0,
    fieldDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    fieldName: 'status',
    fieldComment: '状态',
    fieldType: ['char'],
    columnSize: 1,
    scale: 0,
    fieldDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    fieldName: 'is_delete',
    fieldComment: '是否删除',
    fieldType: ['char'],
    columnSize: 1,
    scale: 0,
    fieldDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    fieldName: 'created_at',
    fieldComment: '创建时间',
    fieldType: ['datetime'],
    columnSize: 0,
    scale: 0,
    fieldDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    fieldName: 'updated_at',
    fieldComment: '更新时间',
    fieldType: ['datetime'],
    columnSize: 0,
    scale: 0,
    fieldDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    fieldName: 'created_by',
    fieldComment: '创建人',
    fieldType: ['bigint'],
    columnSize: 19,
    scale: 0,
    fieldDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    fieldName: 'updated_by',
    fieldComment: '更新人',
    fieldType: ['bigint'],
    columnSize: 19,
    scale: 0,
    fieldDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    fieldName: 'tenant_id',
    fieldComment: '租户ID',
    fieldType: ['bigint'],
    columnSize: 19,
    scale: 0,
    fieldDefault: '',
    primaryKey: false,
    nullable: true,
  },
];
