// 默认字段列表数据
export const FIELD_TABLE_DATA = [
  {
    columnName: 'id',
    columnComment: '主键',
    jdbcTypeName: ['bigint'],
    columnLength: 19,
    scale: 0,
    columnDefault: '',
    primaryKey: true,
    nullable: false,
  },
  {
    columnName: 'sort',
    columnComment: '排序',
    jdbcTypeName: ['int'],
    columnLength: 19,
    scale: 0,
    columnDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    columnName: 'status',
    columnComment: '状态',
    jdbcTypeName: ['char'],
    columnLength: 1,
    scale: 0,
    columnDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    columnName: 'is_delete',
    columnComment: '是否删除',
    jdbcTypeName: ['char'],
    columnLength: 1,
    scale: 0,
    columnDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    columnName: 'created_at',
    columnComment: '创建时间',
    jdbcTypeName: ['datetime'],
    columnLength: 0,
    scale: 0,
    columnDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    columnName: 'updated_at',
    columnComment: '更新时间',
    jdbcTypeName: ['datetime'],
    columnLength: 0,
    scale: 0,
    columnDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    columnName: 'created_by',
    columnComment: '创建人',
    jdbcTypeName: ['bigint'],
    columnLength: 19,
    scale: 0,
    columnDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    columnName: 'updated_by',
    columnComment: '更新人',
    jdbcTypeName: ['bigint'],
    columnLength: 19,
    scale: 0,
    columnDefault: '',
    primaryKey: false,
    nullable: true,
  },
  {
    columnName: 'tenant_id',
    columnComment: '租户ID',
    jdbcTypeName: ['bigint'],
    columnLength: 19,
    scale: 0,
    columnDefault: '',
    primaryKey: false,
    nullable: true,
  },
];
